apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: logger
spec:
  selector:
    matchLabels:
      app: logger
  replicas: 1
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: quay.io/guanwang/logger:v1.3
        env:
        # 总日志条数
        - name: LINE_TOTAL
          value: '10000000'
        # 每秒日志条数，只支持1,10,100,1000
        - name: LINE_PER_SECOND
          value: '1000'
        # 不限制每秒日志条数，当这个环境变量是true时，会忽略 LINE_PER_SECOND
        - name: NO_SLEEP
          value: 'false'
