kind: ConfigMap
metadata:
  name: filebrowser-config
apiVersion: v1
data:
  .filebrowser.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "/srv"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  replicas: 1
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      # 需提前创建 cluster-role-mount-anyuid.yaml
      # sa需要提前创建，并且赋予相应的权限
      # oc -n <namespace> create sa filebrowser
      # oc -n <namespace> adm policy add-role-to-user system:openshift:scc:hostmount-anyuid -z filebrowser
      serviceAccountName: filebrowser
      containers:
      - name: filebrowser
        image: docker.io/filebrowser/filebrowser
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        volumeMounts:
        - name: nfs-volume
          mountPath: /srv
        - name: config-volume
          mountPath: /
      volumes:
      - name: nfs-volume
        nfs:
          # nfs地址和挂载路径需要更改
          server: 10.72.93.235
          path: /data/nfs
      - name: config-volume
        configMap:
          name: filebrowser-config
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  type: ClusterIP
  selector:
    app: filebrowser
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: filebrowser
  name: filebrowser
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  # 域名需要修改
  host: filebrowser.apps.develop.beautytiger.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: filebrowser
    weight: 100
  tls:
    termination: edge
