apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfsmount
  labels:
    app: nfsmount
spec:
  selector:
    matchLabels:
      app: nfsmount
  replicas: 3
  template:
    metadata:
      labels:
        app: nfsmount
    spec:
      containers:
      - name: nginx
        image: quay.io/bitnami/nginx:1.19.7
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        volumeMounts:
        - name: nfs-volume
          mountPath: /logs
          subPathExpr: $(NAMESPACE)/$(POD_NAME)
      volumes:
      - name: nfs-volume
        nfs: 
          server: 10.72.93.235
          path: /data/nfs
---
apiVersion: v1
kind: Service
metadata:
  name: nfsmount
  labels:
    app: nfsmount
spec:
  type: ClusterIP
  selector:
    app: nfsmount
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nfsmount
  name: nfsmount
spec:
  host: nfsmount-test.apps.develop.beautytiger.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nfsmount
    weight: 100
