# oc -n <namespace> create sa stsnfsmount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stsnfsmount
---
# 需提前创建 cluster-role-mount-anyuid.yaml
# oc -n <namespace> adm policy add-role-to-user system:openshift:scc:hostmount-anyuid -z stsnfsmount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stsnfsmount
  # namespace需要修改
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostmount-anyuid
subjects:
- kind: ServiceAccount
  name: stsnfsmount
  # namespace需要修改
  namespace: test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stsnfsmount
  labels:
    app: stsnfsmount
spec:
  selector:
    matchLabels:
      app: stsnfsmount
  replicas: 3
  template:
    metadata:
      labels:
        app: stsnfsmount
    spec:
      # 对应的sa
      serviceName: "nginx-headless"
      serviceAccountName: stsnfsmount
      containers:
      - name: nginx
        image: quay.io/bitnami/nginx:1.19.7
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        volumeMounts:
        - name: nfs-volume
          mountPath: /logs
          # 如果是pod间共享，则不需要 subPathExpr
          subPathExpr: $(NAMESPACE)/$(POD_NAME)
      volumes:
      - name: nfs-volume
        nfs:
          # nfs地址和挂载路径需要更改
          server: test-ocp-nfs.beautytiger.com
          path: /nfs
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: stsnfsmount
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: stsnfsmount
---
apiVersion: v1
kind: Service
metadata:
  name: stsnfsmount
  labels:
    app: stsnfsmount
spec:
  type: ClusterIP
  selector:
    app: stsnfsmount
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: stsnfsmount
  name: stsnfsmount
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  # 域名需要修改
  host: stsnfsmount-test.apps.dev.beautytiger.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: stsnfsmount
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
