# https://tunein.engineering/implementing-leader-election-for-kubernetes-pods-2477deef8f13
---
apiVersion: v1
kind: Namespace
metadata:
  name: "leader-election-test"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-test
  namespace: "leader-election-test"
  labels:
    app: leader-election-test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: leader-election-test
  namespace: "leader-election-test"
  labels:
    app: leader-election-test
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: leader-election-test
  labels:
    app: leader-election-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-election-test
subjects:
  - name: leader-election-test
    namespace: "leader-election-test"
    kind: ServiceAccount
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: music-pod-test
  namespace: "leader-election-test"
  labels:
    app: leader-election-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leader-election-test
  template:
    metadata:
      labels:
        app: leader-election-test
      annotations:
    spec:
      serviceAccountName: leader-election-test
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    apt-get update;
                    apt-get install -y curl;
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -v --silent http://localhost:4040/ 2>&1 | grep $HOSTNAME
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: leader-election-test
          image: "k8s.gcr.io/leader-elector:0.5"
          args:
          - --election=example
          - --http=0.0.0.0:4040
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4040