apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  nodeSelector:
    kubernetes.io/hostname: mynode
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 99999
    image: docker.io/busybox:1.28.4
    name: busybox
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi