apiVersion: v1
kind: Pod
metadata:
  name: backup-etcd-check
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - 'sleep 99999'
    image: harbor.beautytiger.com/docker.io/centos:rich
    imagePullPolicy: IfNotPresent
    name: backup
    volumeMounts:
    - mountPath: /backup
      name: backup
  volumes:
  - name: backup
    persistentVolumeClaim:
      claimName: backup-etcd
