apiVersion: v1
kind: Service
metadata:
  name: sshd
spec:
  clusterIP: None
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: sshd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  selector:
    matchLabels:
      app: sshd
  serviceName: sshd
  replicas: 3
  template:
    metadata:
      name: sshd
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: harbor.beautytiger.com/docker.io/rastasheep/ubuntu-sshd:18.04
        ports:
        - containerPort: 22
          name: client
